name: grand
channels:
  - conda-forge
  - defaults
dependencies:
  - anyio
  - appdirs
  - argon2-cffi
  - argon2-cffi-bindings
  - asttokens
  - attrs
  - backcall
  - backports
  - backports.functools_lru_cache
  - beautifulsoup4
  - bleach
  - brotlipy
  - bzip2
  - c-ares
  - ca-certificates
  - cairo
  - certifi
  - cffi
  - cfitsio
  - charset-normalizer
  - colorama
  - comm
  - cryptography
  - debugpy
  - decorator
  - defusedxml
  - entrypoints
  - executing
  - expat
  - fftw
  - flit-core
  - font-ttf-dejavu-sans-mono
  - font-ttf-inconsolata
  - font-ttf-source-code-pro
  - font-ttf-ubuntu
  - fontconfig
  - fonts-conda-ecosystem
  - fonts-conda-forge
  - freetype
  - fribidi
  - ftgl
  - gdk-pixbuf
  - gettext
  - giflib
  - gl2ps
  - glew
  - graphite2
  - graphviz
  - gsl
  - gsoap
  - gtk2
  - gts
  - harfbuzz
  - icu
  - idna
  - importlib-metadata
  - importlib_metadata
  - importlib_resources
  - ipykernel
  - ipyparallel
  - ipython
  - ipython_genutils
  - jedi
  - jinja2
  - jpeg
  - jsonschema
  - jupyter_client
  - jupyter_core
  - jupyter_events
  - jupyter_server
  - jupyter_server_terminals
  - jupyterlab_pygments
  - krb5
  - lerc
  - libblas
  - libcblas
  - libcurl
  - libdeflate
  - libedit
  - libev
  - libffi
  - libgd
  - libglib
  - libhwloc
  - libiconv
  - liblapack
  - libnghttp2
  - libopenblas
  - libpng
  - librsvg
  - libsodium
  - libsqlite
  - libssh2
  - libtiff
  - libwebp
  - libwebp-base
  - libxml2
  - libzlib
  - llvmlite
  - lz4-c
  - markupsafe
  - matplotlib-inline
  - metakernel
  - mistune
  - nbclassic
  - nbclient
  - nbconvert
  - nbconvert-core
  - nbconvert-pandoc
  - nbformat
  - ncurses
  - nest-asyncio
  - nlohmann_json
  - notebook
  - notebook-shim
  - numba
  - numpy
  - openssl
  - packaging
  - pandoc
  - pandocfilters
  - pango
  - parso
  - pcre
  - pcre2
  - pexpect
  - pickleshare
  - pip
  - pixman
  - pkgutil-resolve-name
  - platformdirs
  - pooch
  - portalocker
  - prometheus_client
  - prompt-toolkit
  - psutil
  - ptyprocess
  - pure_eval
  - pycparser
  - pygments
  - pyopenssl
  - pyrsistent
  - pysocks
  - pythia8
  - python
  - python-dateutil
  - python-fastjsonschema
  - python-json-logger
  - python_abi
  - pyyaml
  - pyzmq
  - readline
  - requests
  - rfc3339-validator
  - rfc3986-validator
  - rhash
  - root
  - root_base
  - scipy
  - scitokens-cpp
  - send2trash
  - setuptools
  - six
  - sniffio
  - soupsieve
  - sqlite
  - stack_data
  - tbb
  - terminado
  - tinycss2
  - tk
  - tornado
  - tqdm
  - traitlets
  - typing-extensions
  - typing_extensions
  - tzdata
  - urllib3
  - vdt
  - vector-classes
  - wcwidth
  - webencodings
  - websocket-client
  - wheel
  - xxhash
  - xz
  - yaml
  - zeromq
  - zipp
  - zlib
  - zstd
  - pip:
      - appjar
      - asdf
      - asdf-standard
      - asdf-transform-schemas
      - asdf-unit-schemas
      - asteval
      - astroid
      - astropy
      - awkward
      - awkward-cpp
      - bcrypt
      - black
      - click
      - contourpy
      - coverage
      - cycler
      - dill
      - exceptiongroup
      - fonttools
      - future
      - greenlet
      - h5py
      - iniconfig
      - isort
      - jmespath
      - kiwisolver
      - lazy-object-proxy
      - lmfit
      - lxml
      - matplotlib
      - mccabe
      - mypy
      - mypy-extensions
      - paramiko
      - pathspec
      - pillow
      - pluggy
      - py
      - pyerfa
      - pylint
      - py-minisign
      - pynacl
      - pyparsing
      - pytest
      - scp
      - semantic-version
      - sqlalchemy
      - sshtunnel
      - tokenize-rt
      - toml
      - tomli
      - tomlkit
      - uncertainties
      - uproot
      - wrapt
      - plotly
      - pandas
