FROM rootproject/root:6.24.06-ubuntu20.04

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

RUN apt-get update && apt -y upgrade\
&& apt-get install -y git\
&& apt install -y make\
&& apt install -y libpng-dev\
&& apt install -y pip

RUN PATH=.:$PATH

######################################################
# We install all the infra and server python packages
######################################################
COPY requirements.txt /usr/src/app
RUN python3 -m pip install --upgrade pip\
&& python3 -m pip install --no-cache-dir -r requirements.txt


ENV USR grand
ENV GRAND_UID 208
ENV GRAND_GID 998

EXPOSE 5537
