# -*- coding: utf-8 -*-
r"""Writes ``docs/source/data_format.rst``, the field-by-field reference of the ROOT trees.

The page is generated from the tree classes themselves -- the same field
declarations, types, units and descriptions the code uses -- so it cannot
drift from the format.  ``docs/source/conf.py`` runs it at the start of every
documentation build; it can also be run by hand::

    python docs/dev/make_data_format.py
"""

import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
TARGET = ROOT / "docs" / "source" / "data_format.rst"

#: Fields of the Python objects that are not branches of the tree.
NOT_BRANCHES = {"is_tchain"}

INTRO = """\
Data format reference
=====================

..
   Generated by docs/dev/make_data_format.py from the tree classes; do not
   edit.  To change a description, edit the string under the field in
   grand/dataio/event_trees.py or grand/dataio/run_trees.py.

Every field of every tree GRANDlib reads and writes, with its type, unit and
meaning.  Run-level trees hold what stays the same for a whole run, one entry
per run; event-level trees hold one entry per event.  :doc:`datamodel`
explains how the trees fit together and how to read them.

Each tree is stored in its own file, named after the tree type:
``shower_*.root`` for ``TShower``, ``run_*.root`` for ``TRun`` and so on.
"""


def _split(kind):
    r"""Splits a field kind such as ``float32, in GeV`` into type and unit.

    Parameters
    ----------
    kind : str
        As :func:`grand.basis.fielddoc._fields` gives it.

    Returns
    -------
    tuple of str
        The type and the unit, the unit empty when there is none.
    """
    if ", in " in kind:
        kind, unit = kind.rsplit(", in ", 1)
        return kind, unit
    return kind, ""


def _cell(text):
    r"""Returns `text` on one line, safe inside a list-table cell.

    Parameters
    ----------
    text : str
        A description, possibly over several lines.

    Returns
    -------
    str
        The text with its lines joined, or a dash when it is empty.
    """
    text = " ".join(text.split())
    if not text:
        return "--"
    return text if text[-1] in ".!?)" else text + "."


def _trees():
    r"""Returns the tree classes, run-level first, in the order of their modules.

    Returns
    -------
    list of tuple
        ``(heading, classes)`` for the run-level and the event-level trees.
    """
    import inspect

    from grand.dataio import event_trees, run_trees
    from grand.dataio.data_tree import DataTree

    def classes(module):
        found = [obj for name, obj in vars(module).items()
                 if inspect.isclass(obj) and issubclass(obj, DataTree)
                 and obj.__module__ == module.__name__ and name.startswith("T")]
        return sorted(found, key=lambda c: inspect.getsourcelines(c)[1])

    return [("Run-level trees", classes(run_trees)),
            ("Event-level trees", classes(event_trees))]


def render():
    r"""Returns the text of the page.

    Returns
    -------
    str
        reStructuredText.
    """
    from grand.basis.fielddoc import _fields

    out = [INTRO]
    for heading, classes in _trees():
        out += ["", heading, "-" * len(heading), ""]
        for cls in classes:
            summary = _cell((cls.__doc__ or "").strip().split("\n\n")[0])
            fields = [f for f in _fields(cls) if f[0] not in NOT_BRANCHES]
            name = "``%s``" % cls.__name__
            out += [name, "~" * len(name), "",
                    "%s  File: ``%s_*.root``; API: :class:`~%s.%s`."
                    % (summary, cls._type, cls.__module__, cls.__name__), "",
                    ".. list-table::", "   :header-rows: 1", "   :widths: 22 22 10 46", "",
                    "   * - Field", "     - Type", "     - Unit", "     - Description"]
            for field, kind, text in fields:
                kind, unit = _split(kind)
                out += ["   * - ``%s``" % field, "     - ``%s``" % kind,
                        "     - %s" % (unit or "--"), "     - %s" % _cell(text)]
            out.append("")
    return "\n".join(out).rstrip() + "\n"


def write(target=TARGET):
    r"""Writes the page, only if its text changed.

    Parameters
    ----------
    target : pathlib.Path, optional
        Where to write it; ``docs/source/data_format.rst`` by default.

    Returns
    -------
    bool
        True if the file was written.
    """
    text = render()
    if target.exists() and target.read_text() == text:
        return False
    target.write_text(text)
    return True


if __name__ == "__main__":
    sys.path.insert(0, str(ROOT))
    print("wrote" if write() else "unchanged", TARGET)
