FROM rootproject/root:6.26.02-ubuntu20.04

# Add package for C compilation 
#RUN apt-get update && apt -y upgrade\
RUN apt-get update\
&& apt-get install -y git\
&& apt install -y make\
&& apt install -y libpng-dev\
&& apt install -y pip


RUN mkdir -p /opt/grandlib

# install python lib for grand lib
COPY requirements.txt /opt/grandlib/requirements_grandlib.txt

RUN python3 -m pip install --upgrade pip &&\
    python3 -m pip install --no-cache-dir -r /opt/grandlib/requirements_grandlib.txt

# install the notebook package
RUN pip install --no-cache notebook jupyterlab &&\
    pip install --no-cache ipynb

# create user with a home directory
ARG NB_USER=jovyan
ARG NB_UID=1000
ENV USER ${NB_USER}
ENV HOME /home/${NB_USER}

RUN adduser --disabled-password \
    --gecos "Default user" \
    --uid ${NB_UID} \
    ${NB_USER}

WORKDIR ${HOME}
USER ${USER}

# Make sure the contents of our repo are in ${HOME}
#COPY . ${HOME}
USER root
RUN chown -R ${NB_UID} ${HOME}
USER ${NB_USER}


RUN git clone https://github.com/grand-mother/grand.git

WORKDIR ${HOME}/grand
COPY HorizonAntenna_EWarm_leff_loaded.npy ${HOME}/grand/grand/tools/data/huge/HorizonAntenna_EWarm_leff_loaded.npy
run touch ${HOME}/grand/grand/tools/data/huge/use_instead_HOME.grand
RUN env/setup.sh &&\
    pytest tests


ENV PYTHONPATH="${HOME}/grand:${PYTHONPATH}"



